const questions = [
  { id: 1, text: "当伴侣没有及时回复消息时，我会忍不住猜测对方是不是对我不耐烦了。", dimension: "anxious" },
  { id: 2, text: "我经常担心伴侣会突然离开我、不再喜欢我。", dimension: "anxious" },
  { id: 3, text: "我非常渴望和伴侣亲密，有时可能会让对方感到压力。", dimension: "anxious" },
  { id: 4, text: "如果伴侣和异性走得较近，我会立刻感到不安、吃醋或嫉妒。", dimension: "anxious" },
  { id: 5, text: "我需要伴侣反复表达爱意与在乎，才能真正感到安心。", dimension: "anxious" },
  { id: 6, text: "关系一出现矛盾，我就会陷入焦虑，很难专心做其他事。", dimension: "anxious" },
  { id: 7, text: '我容易把小事放大，觉得"不在意细节就是不够爱我"。', dimension: "anxious" },
  { id: 8, text: "即使伴侣已经很用心，我仍常常觉得对方不够关注我。", dimension: "anxious" },
  { id: 9, text: "为了维持关系和谐，我有时会委屈自己的真实感受。", dimension: "anxious" },
  { id: 10, text: "伴侣稍微冷淡一点，我就会立刻怀疑是不是自己哪里做错了。", dimension: "anxious" },
  { id: 11, text: "当伴侣想要更亲密时，我会下意识想拉开一点距离。", dimension: "avoidant" },
  { id: 12, text: "我不习惯在伴侣面前暴露脆弱、难过或软弱的一面。", dimension: "avoidant" },
  { id: 13, text: "我认为依赖别人是不安全的，凡事还是靠自己更可靠。", dimension: "avoidant" },
  { id: 14, text: "即使在恋爱中，我也需要大量个人空间，否则会感到窒息。", dimension: "avoidant" },
  { id: 15, text: "当伴侣情绪激动时，我会不知所措，只想逃离或沉默。", dimension: "avoidant" },
  { id: 16, text: "对我来说，保持独立比亲密关系更重要。", dimension: "avoidant" },
  { id: 17, text: "我不擅长口头表达爱意，觉得用行动证明就足够。", dimension: "avoidant" },
  { id: 18, text: "伴侣抱怨我不够关心时，我常会觉得是对方太粘人、要求太多。", dimension: "avoidant" },
  { id: 19, text: "我很少主动向伴侣倾诉内心深处的想法和感受。", dimension: "avoidant" },
  { id: 20, text: "分手后我能较快恢复，不会长时间沉浸在难过里。", dimension: "avoidant" },
  { id: 21, text: "我相信伴侣是值得信赖的，不会轻易怀疑对方的真心。", dimension: "secure" },
  { id: 22, text: "我可以自在地向伴侣表达需求与感受，不担心被拒绝或嘲笑。", dimension: "secure" },
  { id: 23, text: "当伴侣需要个人空间时，我能理解并给予支持。", dimension: "secure" },
  { id: 24, text: "发生矛盾时，我愿意冷静沟通，而不是争吵或冷战。", dimension: "secure" },
  { id: 25, text: "我相信自己值得被爱，不会因一次争执就否定整段关系。", dimension: "secure" },
  { id: 26, text: "我能平衡亲密与独立，既不害怕靠近，也不抗拒独处。", dimension: "secure" },
  { id: 27, text: "我乐于和伴侣分享喜怒哀乐，也愿意认真倾听对方。", dimension: "secure" },
  { id: 28, text: "我尊重伴侣有自己的朋友和社交圈，不会因此感到威胁。", dimension: "secure" },
  { id: 29, text: "即使伴侣暂时不在身边，我也不会过度焦虑或胡思乱想。", dimension: "secure" },
  { id: 30, text: "我相信关系中的问题可以一起解决，而非天生不合适。", dimension: "secure" }
]

module.exports = { questions }